[package]
name = "combustion_graphing"
version = "0.1.0"
authors = ["Aaron Trent <novacrazy@gmail.com>"]

[dev-dependencies]
image = "0.12.3"

[dependencies.combustion_common]
path = "../combustion_common"