[package]
name = "combustion_graphing"
version = "0.1.0"
authors = ["Aaron Trent <novacrazy@gmail.com>"]

[dependencies]
image = "0.12.3"
rayon = "0.7.0"

[dependencies.combustion_common]
path = "../combustion_common"